spring.application.name=user-service
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:1985/employeedata
#spring.datasource.url=jdbc:postgresql://localhost:5433/employeedata
spring.datasource.username=postgres
spring.datasource.password=Postgres@2026



spring.jpa.hibernate.ddl-auto=update
     # or create, create-drop, none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

eureka.client.service-url.defaultZone=http://localhost:8761/eureka