# 1️⃣ Base image: lightweight Java 17
FROM eclipse-temurin:17-jdk-alpine
#FROM openjdk:17-jdk-alpine

# 2️⃣ Set working directory inside container
WORKDIR /app

# 3️⃣ Copy built jar into container
COPY target/user-service-0.0.1-SNAPSHOT.jar app.jar

# 4️⃣ Expose application port
EXPOSE 8080

# 5️⃣ Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
