version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: employeedata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres@2026
    ports:
      - "5432:5432"

  user-service:
    build: .
    container_name: user-service
    ports:
      - "2002:2002"
    depends_on:
      - postgres
